stderr of test 'alastair_udf_mergetable_bug` in directory 'sql/test/scripts` itself:


# 14:10:49 >  
# 14:10:49 >  "/usr/bin/python2" "alastair_udf_mergetable_bug.py" "alastair_udf_mergetable_bug"
# 14:10:49 >  


# 14:10:50 >  
# 14:10:50 >  "Done."
# 14:10:50 >  

