stdout of test 'python-microseconds.Bug-3439` in directory 'sql/test/BugTracker-2014` itself:


# 17:15:02 >  
# 17:15:02 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=32843" "--set" "mapi_usock=/var/tmp/mtest-19946/.s.monetdb.32843" "--set" "monet_prompt=" "--forcemito" "--set" "mal_listing=2" "--dbpath=/home/sjoerd/Monet-stable/var/MonetDB/mTests_sql_test_BugTracker-2014" "--set" "mal_listing=0"
# 17:15:02 >  


# 09:18:23 >  
# 09:18:23 >  "Done."
# 09:18:23 >  

