stderr of test 'dependency_column_on_sequence.Bug-6618` in directory 'sql/test/BugTracker-2018` itself:


# 15:00:25 >  
# 15:00:25 >  "/usr/local/opt/python@2/bin/python2.7" "dependency_column_on_sequence.Bug-6618.py" "dependency_column_on_sequence.Bug-6618"
# 15:00:25 >  


# 15:43:24 >  
# 15:43:24 >  "Done."
# 15:43:24 >  

