stderr of test 'userCallFunction` in directory 'sql/test/Users` itself:


# 12:59:01 >  
# 12:59:01 >  "/usr/bin/python3.9" "userCallFunction.SQL.py" "userCallFunction"
# 12:59:01 >  


# 12:59:02 >  
# 12:59:02 >  "Done."
# 12:59:02 >  

