stderr of test 'remote-table-non-existent-column.Bug-6750` in directory 'sql/test/BugTracker-2019` itself:


# 10:42:19 >  
# 10:42:19 >  "/usr/bin/python3" "remote-table-non-existent-column.Bug-6750.py" "remote-table-non-existent-column.Bug-6750"
# 10:42:19 >  


# 10:42:21 >  
# 10:42:21 >  "Done."
# 10:42:21 >  

