stderr of test 'shutdown.Bug-6182` in directory 'sql/test/BugTracker-2017` itself:


# 10:26:41 >  
# 10:26:41 >  "/usr/bin/python3.9" "shutdown.Bug-6182.SQL.py" "shutdown.Bug-6182"
# 10:26:41 >  



# 10:26:42 >  
# 10:26:42 >  "Done."
# 10:26:42 >  

