stderr of test 'groupby_error` in directory 'sql/test/miscellaneous` itself:


# 10:56:46 >  
# 10:56:46 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=36667" "--set" "mapi_usock=/var/tmp/mtest-13678/.s.monetdb.36667" "--set" "monet_prompt=" "--forcemito" "--dbpath=/home/ferreira/repositories/MonetDB-Apr2019/BUILD/var/MonetDB/mTests_sql_test_miscellaneous" "--set" "embedded_c=true"
# 10:56:46 >  

MAPI  = (monetdb) /var/tmp/mtest-915189/.s.monetdb.30839
QUERY = SELECT parent."sys_id" FROM "kagami_dump"."test_task" parent INNER JOIN "kagami_dump"."test_task" child ON child."parent" = parent."sys_id" GROUP BY parent."sys_id" HAVING count(child."sys_id") >= 1 ORDER BY parent."number"; --error, parent."number" requires an aggregate function
ERROR = !SELECT: no such column 'parent.number'
CODE  = 42S22
MAPI  = (monetdb) /var/tmp/mtest-561836/.s.monetdb.32526
QUERY = SELECT col0 FROM tab0 ORDER BY sys.tab0.col0; --error, TODO
ERROR = !TODO: column names of level >= 3
CODE  = 42000

# 10:56:47 >  
# 10:56:47 >  "Done."
# 10:56:47 >  

